version: '3.1'
services:
  webserver:
    build:
      context: .
      dockerfile: Docker/webserver/Dockerfile
    depends_on:
      - mariadb
    user: "1000:1000"
    ports:
      - "8002:80"
      - "4432:443"
    volumes:
      - ./:/var/www/html
      - ./Docker/webserver/php.ini:/usr/local/etc/php/php.ini
    env_file:
      - .env
    environment:
      - DB_HOST=mariadb
  mariadb:
    build:
      context: .
      dockerfile: Docker/mariadb/Dockerfile
    environment:
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_RANDOM_ROOT_PASSWORD='yes'
    volumes:
      - mariadb:/var/lib/mysql
      - ./Docker/mariadb/database:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    depends_on:
      - mariadb
    ports:
      - "9082:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${DB_PASSWORD}
      - UPLOAD_LIMIT=200M
volumes:
  mariadb:
